### ISSUE TITLE
[Bug] node-sass incompatible with MDC

### ISSUE THREAD

**Issue by Pk13055** [thgh/rollup-plugin-scss#41]
Here's the traceback:
```bash
src/index.js → dist/bundle.js...
[!] (plugin css) Error: Invalid CSS after "@include mixins": expected 1 selector or at-rule, was ".core-styles;"
Error: Invalid CSS after "@include mixins": expected 1 selector or at-rule, was ".core-styles;"
    at Object.module.exports.renderSync (./node_modules/node-sass/lib/index.js:441:16)
    at compileToCSS (./node_modules/rollup-plugin-scss/index.cjs.js:23:40)
    at Object.generateBundle (./node_modules/rollup-plugin-scss/index.cjs.js:88:17)
    at ./node_modules/rollup/dist/shared/node-entry.js:13113:25
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```
Here's the `rollup.config.js`:
```js
import svelte from 'rollup-plugin-svelte'
import resolve from '@rollup/plugin-node-resolve'
import commonjs from '@rollup/plugin-commonjs'
import serve from 'rollup-plugin-serve'
import scss from 'rollup-plugin-scss'

export default {
    input: 'src/index.js',
    output: {
        //  sourcemap: true,
        file: 'dist/bundle.js',
        format: 'iife',
        name: 'app'
    },
    plugins: [
        svelte({
            dev: true,
            emitCss: true,
        }),
        resolve(),
        commonjs(),
        scss({
            output: 'dist/bundle.css',
            failOnError: true
        }),
        serve({
            contentBase: 'dist',
            verbose: true,
            host: '0.0.0.0',
            port: 8000,
            headers: {'Access-Control-Allow-Origin': '*'}
        })
    ],
    watch: {
        clearScreen: false
    }
}

```

**Comment by Pk13055** [comment]
#39 will help fix a lot of the issues, inspite of some sacrificed speed

**Comment by Pk13055** [comment]
Also,
![Screenshot from 2020-02-19 02-54-48](https://user-images.githubusercontent.com/13479308/74779371-5c5e3680-52c3-11ea-877d-aed191462491.png)

**Comment by Pk13055** [comment]
Okay so turns out it works with node-8. There's a dockerized version of the app at `pk13055/svelte-template:latest`
